version: '3'
services:
    app:
        build:
            context: ../
            dockerfile: docker/Dockerfile
        working_dir: /var/www
        volumes:
            - ../:/var/www
        networks:
            - app-network
    webserver:
        image: nginx:alpine
        ports:
            - "80:80"
        volumes:
            - ../:/var/www
            - ./nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - app-network
    mariadb:
        image: 'mariadb:10'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - 'dbdata:/var/lib/mysql'
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}" ]
            retries: 3
            timeout: 5s
        networks:
            - app-network
networks:
  app-network:
    driver: bridge
volumes:
  dbdata:
    driver: local
